[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
fxhash = "0.2.1"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
tiktoken-rs = "0.6.0"
